In [ ]:
!pip install scanpy --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 85.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.6/176.6 kB 14.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 104.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.7/295.7 kB 19.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 104.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.

In [ ]:
import numpy as np
import pandas as pd
import anndata as ad
from scipy.sparse import csr_matrix
print(ad.__version__)

0.12.10

/tmp/ipykernel_2372/2319192822.py:5: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('anndata')` instead.
  print(ad.__version__)

In [ ]:
counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)
adata

AnnData object with n_obs × n_vars = 100 × 2000

In [ ]:
adata.X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 126772 stored elements and shape (100, 2000)>

In [ ]:
adata.obs_names = [f"Cell_{i:d}" for i in range(adata.n_obs)]
adata.var_names = [f"Gene_{i:d}" for i in range(adata.n_vars)]
print(adata.obs_names[:10])

Index(['Cell_0', 'Cell_1', 'Cell_2', 'Cell_3', 'Cell_4', 'Cell_5', 'Cell_6',
       'Cell_7', 'Cell_8', 'Cell_9'],
      dtype='object')

In [ ]:
adata[["Cell_1", "Cell_10"], ["Gene_5", "Gene_1900"]]

View of AnnData object with n_obs × n_vars = 2 × 2

In [ ]:
ct = np.random.choice(["B", "T", "Monocyte"], size=(adata.n_obs,))
adata.obs["cell_type"] = pd.Categorical(ct)  # Categoricals are preferred for efficiency
adata.obs

        cell_type
Cell_0          B
Cell_1          T
Cell_2          B
Cell_3          B
Cell_4          T
...           ...
Cell_95         T
Cell_96         T
Cell_97         B
Cell_98  Monocyte
Cell_99  Monocyte

[100 rows x 1 columns]

In [ ]:
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'

In [ ]:
bdata = adata[adata.obs.cell_type == "B"]
bdata

View of AnnData object with n_obs × n_vars = 35 × 2000
    obs: 'cell_type'

In [ ]:
adata.obsm["X_umap"] = np.random.normal(0, 1, size=(adata.n_obs, 2))
adata.varm["gene_stuff"] = np.random.normal(0, 1, size=(adata.n_vars, 5))
adata.obsm

AxisArrays with keys: X_umap

In [ ]:
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'
    obsm: 'X_umap'
    varm: 'gene_stuff'

In [ ]:
adata.uns["random"] = [1, 2, 3]
adata.uns

OrderedDict([('random', [1, 2, 3])])

In [ ]:
adata.layers["log_transformed"] = np.log1p(adata.X)
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'
    uns: 'random'
    obsm: 'X_umap'
    varm: 'gene_stuff'
    layers: 'log_transformed'

In [ ]:
adata.to_df(layer="log_transformed")

,Gene_0,Gene_1,Gene_2,Gene_3,Gene_4,Gene_5,Gene_6,Gene_7,Gene_8,Gene_9,...,Gene_1990,Gene_1991,Gene_1992,Gene_1993,Gene_1994,Gene_1995,Gene_1996,Gene_1997,Gene_1998,Gene_1999
Cell_0,0.693147,1.098612,0.000000,1.386294,0.000000,0.000000,0.693147,1.386294,0.000000,0.693147,...,0.000000,0.000000,0.693147,1.098612,1.098612,0.000000,0.000000,0.000000,0.693147,0.693147
Cell_1,0.693147,1.098612,0.693147,0.693147,1.098612,0.000000,0.000000,1.098612,0.693147,0.693147,...,1.098612,0.000000,0.693147,0.000000,0.000000,0.693147,1.386294,0.000000,1.098612,0.693147
Cell_2,1.098612,0.693147,0.693147,0.693147,0.693147,0.000000,1.386294,1.098612,1.386294,0.693147,...,0.000000,0.693147,0.693147,0.000000,0.693147,0.000000,1.098612,0.000000,0.000000,0.693147
Cell_3,1.098612,0.000000,0.000000,1.098612,0.000000,0.000000,0.693147,0.000000,1.098612,0.000000,...,0.693147,0.000000,0.693147,1.098612,1.098612,1.098612,0.000000,0.000000,0.693147,0.000000
Cell_4,1.386294,1.386294,0.693147,1.098612,0.000000,0.000000,0.693147,0.693147,0.693147,0.693147,...,0.693147,0.693147,0.000000,0.000000,0.693147,0.000000,0.693147,0.000000,1.609438,1.386294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cell_95,0.000000,0.693147,0.693147,0.693147,1.098612,0.000000,1.386294,0.693147,0.000000,0.693147,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,0.000000,0.000000,1.098612,1.098612
Cell_96,0.693147,0.693147,1.386294,0.693147,0.693147,0.000000,1.386294,0.693147,0.000000,0.000000,...,0.000000,0.693147,0.693147,0.000000,0.693147,0.693147,0.000000,0.693147,1.386294,0.000000
Cell_97,0.693147,0.000000,0.693147,0.693147,1.098612,0.000000,0.000000,0.000000,1.098612,0.000000,...,0.693147,0.000000,0.693147,1.098612,0.693147,1.386294,1.098612,0.000000,0.693147,1.098612
Cell_98,0.000000,0.000000,0.693147,1.098612,1.098612,1.386294,1.098612,0.693147,0.693147,0.000000,...,0.693147,0.000000,1.386294,0.000000,1.386294,0.000000,0.693147,0.000000,0.000000,1.098612
Cell_99,0.693147,0.000000,0.000000,0.693147,1.098612,0.000000,0.000000,0.693147,0.693147,1.098612,...,0.693147,0.693147,0.000000,0.693147,0.693147,0.000000,1.098612,0.693147,0.000000,0.693147

In [ ]:
adata.write('my_results.h5ad', compression="gzip")

In [ ]:
!apt-get install -y hdf5-tools

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  hdf5-tools
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 347 kB of archives.
After this operation, 1,255 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 hdf5-tools amd64 1.10.7+repack-4ubuntu2 [347 kB]
Fetched 347 kB in 0s (2,976 kB/s)
Selecting previously unselected package hdf5-tools.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../hdf5-tools_1.10.7+repack-4ubuntu2_amd64.deb ...
Unpacking hdf5-tools (1.10.7+repack-4ubuntu2) ...
Setting up hdf5-tools (1.10.7+repack-4ubuntu2) ...
Processing triggers for man-db (2.10.2-1) ...

In [ ]:
!h5ls 'my_results.h5ad'

X                        Group
layers                   Group
obs                      Group
obsm                     Group
obsp                     Group
uns                      Group
var                      Group
varm                     Group
varp                     Group

In [ ]:
obs_meta = pd.DataFrame({
        'time_yr': np.random.choice([0, 2, 4, 8], adata.n_obs),
        'subject_id': np.random.choice(['subject 1', 'subject 2', 'subject 4', 'subject 8'], adata.n_obs),
        'instrument_type': np.random.choice(['type a', 'type b'], adata.n_obs),
        'site': np.random.choice(['site x', 'site y'], adata.n_obs),
    },
    index=adata.obs.index,    # these are the same IDs of observations as above!
)

In [ ]:
adata = ad.AnnData(adata.X, obs=obs_meta, var=adata.var)

In [ ]:
print(adata)

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'

In [ ]:
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'

In [ ]:
adata[:5, ['Gene_1', 'Gene_3']]

View of AnnData object with n_obs × n_vars = 5 × 2
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'

In [ ]:
adata_subset = adata[:5, ['Gene_1', 'Gene_3']].copy()

In [ ]:
print(adata[:3, 'Gene_1'].X.toarray().tolist())
adata[:3, 'Gene_1'].X = [0, 0, 0]
print(adata[:3, 'Gene_1'].X.toarray().tolist())

[[2.0], [2.0], [1.0]]
[[0.0], [0.0], [0.0]]

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:630: FutureWarning: Setting element `.X` of view of `AnnData` object will obey copy-on-write semantics in the next minor release.
  if self._handle_view_X_cow(value):
/tmp/ipykernel_2372/2822107891.py:2: ImplicitModificationWarning: Modifying `X` on a view results in data being overridden
  adata[:3, 'Gene_1'].X = [0, 0, 0]

In [ ]:
adata_subset = adata[:3, ['Gene_1', 'Gene_2']]

In [ ]:
adata_subset

View of AnnData object with n_obs × n_vars = 3 × 2
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'

In [ ]:
adata_subset.obs['foo'] = range(3)

/tmp/ipykernel_2372/2955902014.py:1: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata_subset.obs['foo'] = range(3)

In [ ]:
adata[adata.obs.time_yr.isin([2, 4])].obs.head()

        time_yr subject_id instrument_type    site
Cell_1        2  subject 2          type a  site y
Cell_4        2  subject 2          type b  site y
Cell_6        2  subject 2          type b  site y
Cell_8        4  subject 4          type b  site y
Cell_9        4  subject 4          type b  site x

In [ ]:
adata = ad.read_h5ad('my_results.h5ad', backed='r')

In [ ]:
adata.isbacked

True

In [ ]:
adata.filename

PosixPath('my_results.h5ad')

In [ ]:
adata.file.close()